#!/usr/bin/env bash
# tests/test_pe_doctor_coverage.sh — pe doctor must report how much of the
# engine a project actually runs, and must count shim-routed hooks.
#
# Two defects, both found by the adoption audit:
#
#   1. `pe doctor` answered "can the configured hooks run?" and never "how
#      many of the engine's hooks is this project configured to run?". A
#      capability nobody runs rots unnoticed and gets rebuilt, worse, by the
#      project that needed it. Origyn hand-wrote a CLAUDE.md size gate at
#      40/60 KB while hooks/claude-md-size.sh sat unused with a stricter
#      12/20 KB standard; its CLAUDE.md reached 80,437 bytes.
#
#   2. The count read only the FIRST token of each `entry:`. A project that
#      routes hooks through its own shim —
#          entry: scripts/hooks/engine.sh code-review-trailer.sh
#      — was counted as running one hook called `engine.sh`. pe doctor
#      reported "2 hook(s)" for Origyn, which runs six.

set -uo pipefail
SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENGINE="$(cd "$SELF_DIR/.." && pwd)"
PE="$ENGINE/scripts/pe"

PASS=0; FAIL=0
ok()  { echo "  ✓ $1"; PASS=$((PASS+1)); }
bad() { echo "  ✗ $1"; FAIL=$((FAIL+1)); }

TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
echo "test_pe_doctor_coverage"

SHIPPED=$(find "$ENGINE/hooks" -name '*.sh' -not -name '_*' | wc -l | tr -d ' ')

# ─── a project that routes three engine hooks through its own shim ──
P="$TMP/shimmed"
mkdir -p "$P/scripts/hooks"
git -C "$P" init -q
git -C "$P" config user.email t@t.t
git -C "$P" config user.name t
cat > "$P/.pre-commit-config.yaml" <<YAML
repos:
  - repo: local
    hooks:
      - id: engine-secrets
        name: secrets
        entry: scripts/hooks/engine.sh secrets-scan.sh
        language: script
        stages: [pre-commit]
      - id: engine-review
        name: review
        entry: scripts/hooks/engine.sh code-review-trailer.sh
        language: script
        stages: [commit-msg]
      - id: engine-size
        name: size
        entry: env ENGINE_CLAUDE_MD_WARN=30000 scripts/hooks/engine.sh claude-md-size.sh
        language: script
        stages: [pre-commit]
      - id: own-thing
        name: a hook of its own
        entry: scripts/pre-commit.sh
        language: script
        stages: [pre-commit]
YAML
printf '#!/usr/bin/env bash\nexit 0\n' > "$P/scripts/hooks/engine.sh"
printf '#!/usr/bin/env bash\nexit 0\n' > "$P/scripts/pre-commit.sh"
chmod +x "$P/scripts/hooks/engine.sh" "$P/scripts/pre-commit.sh"
mkdir -p "$P/.git/hooks"
printf '#!/usr/bin/env bash\n# File generated by pre-commit\nINSTALL_PYTHON=x\n' \
    > "$P/.git/hooks/pre-commit"
chmod +x "$P/.git/hooks/pre-commit"
git -C "$P" add -A && git -C "$P" commit -qm base --no-verify

OUT=$("$PE" doctor --json "$P" 2>/dev/null)
DETAIL=$(printf '%s' "$OUT" | "${PE_PYTHON:-python3}" -c '
import json, sys
d = json.load(sys.stdin)
row = next((c for c in d["checks"] if c["name"] == "engine hook coverage"), None)
print(row["detail"] if row else "")
')

[ -n "$DETAIL" ] && ok "pe doctor reports an engine hook coverage row" \
                 || bad "no coverage row in pe doctor --json output"

case "$DETAIL" in
    "3 of $SHIPPED engine hooks wired"*)
        ok "shim-routed hooks are counted (3 of $SHIPPED)" ;;
    *)
        bad "expected '3 of $SHIPPED engine hooks wired…', got: $DETAIL" ;;
esac

case "$DETAIL" in
    *"not wired: "*) ok "coverage row names hooks that are not wired" ;;
    *) bad "coverage row does not name what is missing: $DETAIL" ;;
esac

# The project's own pre-commit.sh must not be counted as an engine hook.
case "$DETAIL" in
    *pre-commit.sh*) bad "counted the project's own script as an engine hook" ;;
    *) ok "a project's own hook script is not counted as the engine's" ;;
esac

# ─── a project wiring nothing gets a WARN, not silence ──────────────
Q="$TMP/bare"
mkdir -p "$Q"; git -C "$Q" init -q
STATUS=$("$PE" doctor --json "$Q" 2>/dev/null | "${PE_PYTHON:-python3}" -c '
import json, sys
d = json.load(sys.stdin)
row = next((c for c in d["checks"] if c["name"] == "engine hook coverage"), None)
print(row["status"] if row else "")
')
[ "$STATUS" = "WARN" ] && ok "a project wiring zero engine hooks is warned" \
                       || bad "expected WARN for zero coverage, got '$STATUS'"

# ─── `pe doctor --json` must work through the CLI at all ────────────
# pe_doctor.py has advertised --json since v0.51.0; cmd_doctor read it as a
# project path and answered "ERROR: --json does not exist".
"$PE" doctor --json "$P" >/dev/null 2>&1 \
    && ok "pe doctor --json exits 0 on a healthy project" \
    || bad "pe doctor --json failed on a healthy project"

echo "  ${PASS} passed, ${FAIL} failed"
[ "$FAIL" -eq 0 ]
