#!/usr/bin/env bash
# tests/test_pe_doctor_hooks.sh — hook reachability (v0.51.0).
#
# `pe verify` proves the engine's files match the manifest. It is silent
# about whether any of them RUN. This is the fixture for the difference.
#
# Contract:
#   - config lists engine hooks + hand-rolled .git/hooks/pre-commit  → exit 1
#   - config lists engine hooks + framework dispatcher installed     → exit 0
#   - config lists engine hooks + no .git/hooks/pre-commit at all    → exit 1
#   - no .pre-commit-config.yaml                                     → exit 0
#   - untracked config warns but does not fail on its own
#
# The failing case is the Origyn 2026-09-04 incident: 10 engine hooks
# configured, 0 executed, CLAUDE.md at 80,437 B against claude-md-size.sh's
# own 20,000 B hard limit. If this fixture ever passes, the check that
# would have caught that has regressed.

set -uo pipefail

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENGINE_DIR="$(cd "$SELF_DIR/.." && pwd)"
DOCTOR="$ENGINE_DIR/scripts/pe_doctor.py"

PASS=0; FAIL=0
ok()   { echo "  ✓ $1"; PASS=$((PASS+1)); }
bad()  { echo "  ✗ $1"; FAIL=$((FAIL+1)); }

py() { command -v python3 >/dev/null && echo python3 || echo python; }
PY="$(py)"

# Build a throwaway project with a given hook arrangement.
# $1 = project dir, $2 = "none" | "handrolled" | "framework"
make_project() {
    local dir="$1" kind="$2"
    mkdir -p "$dir/.git/hooks"
    ( cd "$dir" && git init -q 2>/dev/null ) || true
    cat > "$dir/.pre-commit-config.yaml" <<'YAML'
repos:
  - repo: local
    hooks:
      - id: claude-md-size
        name: CLAUDE.md size
        entry: hooks/claude-md-size.sh
        language: script
      - id: secrets-scan
        name: secrets
        entry: hooks/secrets-scan.sh
        language: script
YAML
    case "$kind" in
        handrolled)
            printf '#!/usr/bin/env bash\n# project gates\nexit 0\n' \
                > "$dir/.git/hooks/pre-commit"
            chmod +x "$dir/.git/hooks/pre-commit" ;;
        framework)
            # The real framework dispatcher carries these markers.
            printf '#!/usr/bin/env bash\n# File generated by pre-commit\nINSTALL_PYTHON=/usr/bin/python3\nexec pre-commit run --config .pre-commit-config.yaml\n' \
                > "$dir/.git/hooks/pre-commit"
            chmod +x "$dir/.git/hooks/pre-commit" ;;
        none) : ;;
    esac
}

run_doctor() { "$PY" "$DOCTOR" "$1" --engine "$ENGINE_DIR" >/dev/null 2>&1; echo $?; }

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

echo "test_pe_doctor_hooks"

# 1 — THE INCIDENT: hooks configured, project script installed, none run.
make_project "$TMP/handrolled" handrolled
rc=$(run_doctor "$TMP/handrolled")
[ "$rc" = "1" ] && ok "hand-rolled pre-commit + configured hooks → exit 1" \
                || bad "hand-rolled bypass NOT detected (exit $rc, expected 1)"

# The message must name the bypass, not just fail.
out=$("$PY" "$DOCTOR" "$TMP/handrolled" --engine "$ENGINE_DIR" 2>&1 || true)
printf '%s' "$out" | grep -q "never invokes them" \
    && ok "failure explains that the hooks are decoration" \
    || bad "failure does not explain the bypass"

# 2 — framework dispatcher installed: the same config is fine.
make_project "$TMP/framework" framework
rc=$(run_doctor "$TMP/framework")
[ "$rc" = "0" ] && ok "framework dispatcher + configured hooks → exit 0" \
                || bad "false positive on a correct install (exit $rc, expected 0)"

# 3 — configured hooks, no git hook at all.
make_project "$TMP/nohook" none
rc=$(run_doctor "$TMP/nohook")
[ "$rc" = "1" ] && ok "configured hooks + no pre-commit hook → exit 1" \
                || bad "missing hook NOT detected (exit $rc, expected 1)"

# 4 — a project that configures nothing is not failed for it.
mkdir -p "$TMP/bare/.git/hooks"; ( cd "$TMP/bare" && git init -q 2>/dev/null ) || true
rc=$(run_doctor "$TMP/bare")
[ "$rc" = "0" ] && ok "no .pre-commit-config.yaml → exit 0" \
                || bad "bare project wrongly failed (exit $rc, expected 0)"

# 5 — untracked config warns, and does not by itself fail a good install.
out=$("$PY" "$DOCTOR" "$TMP/framework" --engine "$ENGINE_DIR" 2>&1 || true)
printf '%s' "$out" | grep -q "untracked" \
    && ok "untracked .pre-commit-config.yaml is reported" \
    || bad "untracked config not reported"

echo "  ${PASS} passed, ${FAIL} failed"
[ "$FAIL" -eq 0 ]
